# Generated by Django 2.0.9 on 2018-12-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight_journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='published_date',
        ),
    ]
