# Generated by Django 2.0.9 on 2018-12-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_journal', '0002_remove_entry_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
